[versions]
app = "3.3.0"
android-billing = "8.3.0"
androidx-activity = "1.12.2"
androidx-annotations = "1.9.1"
androidx-browser = "1.9.0"
androidx-compose-bom = "2026.01.00"
androidx-compose-material3 = "1.5.0-alpha12"
androidx-core = "1.17.0"
androidx-datastore-prefs = "1.2.0"
androidx-glance = "1.2.0-rc01"
androidx-lifecyle = "2.10.0"
androidx-room = "2.8.4"
androidx-splashscreen = "1.2.0"
androidx-startup = "1.2.0"
androidx-work = "2.11.0"
cash-app-turbine = "1.2.1"
circuit = "0.32.0"
coil = "3.3.0"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
foundry = "0.33.1"
google-firebase-crashlytics = "3.0.6"
google-firebase-bom = "34.8.0"
google-services = "4.4.4"
googleid = "1.2.0"
gradle-android = "9.0.0"
gradle-cache-fix = "3.0.3"
gradle-retry = "1.6.4"
haze = "1.7.1"
jdk = "21"
jvmTarget = "17"
kotlin = "2.3.0"
kotlin-coroutines = "1.10.2"
kotlinx-immutable = "0.4.0"
kotlinx-serialization-json = "1.10.0"
ksp = "2.3.4"
ktor = "3.4.0"
lints-compose = "1.4.2"
material = "1.13.0"
material3-adaptive-navigation-suite = "1.4.0"
metro = "0.10.0"
playServicesLocation = "21.3.0"
robolectric = "4.16.1"
slack-lint = "0.11.1"
sortDependencies = "0.16"
spotless = "8.2.0"
supabase = "3.2.6"
test-androidx-ext = "1.3.0"
test-androidx-runner = "1.7.0"
test-junit = "4.13.2"
test-truth = "1.4.5"
timber = "5.0.1"

[libraries]
android-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "android-billing" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "androidx-annotations" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-icons = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidx-compose-material3" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
androidx-datastore-prefs = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore-prefs" }
androidx-glance = { module = "androidx.glance:glance", version.ref = "androidx-glance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "androidx-glance" }
androidx-glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "androidx-glance" }
androidx-glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "androidx-glance" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecyle" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
circuit-codegen = { module = "com.slack.circuit:circuit-codegen", version.ref = "circuit" }
circuit-codegen-annotations = { module = "com.slack.circuit:circuit-codegen-annotations", version.ref = "circuit" }
circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuit" }
circuit-overlay = { module = "com.slack.circuit:circuit-overlay", version.ref = "circuit" }
circuit-retained = { module = "com.slack.circuit:circuit-retained", version.ref = "circuit" }
circuit-runtime = { module = "com.slack.circuit:circuit-runtime", version.ref = "circuit" }
circuit-runtime-presenter = { module = "com.slack.circuit:circuit-runtime-presenter", version.ref = "circuit" }
circuit-runtime-screen = { module = "com.slack.circuit:circuit-runtime-screen", version.ref = "circuit" }
circuit-runtime-ui = { module = "com.slack.circuit:circuit-runtime-ui", version.ref = "circuit" }
circuitx-android = { module = "com.slack.circuit:circuitx-android", version.ref = "circuit" }
circuitx-effects = { module = "com.slack.circuit:circuitx-effects", version.ref = "circuit" }
circuitx-gesture-navigation = { module = "com.slack.circuit:circuitx-gesture-navigation", version.ref = "circuit" }
circuitx-overlays = { module = "com.slack.circuit:circuitx-overlays", version.ref = "circuit" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
google-coreLibraryDesugaring = "com.android.tools:desugar_jdk_libs_minimal:2.1.5"
google-android-material = { module = "com.google.android.material:material", version.ref = "material" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
google-firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug" }
google-firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "google-firebase-bom" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
google-firebase-config = { module = "com.google.firebase:firebase-config" }
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-playservices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
lints-compose = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "lints-compose" }
material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3-adaptive-navigation-suite" }
metrox-android = { module = "dev.zacsweers.metro:metrox-android", version.ref = "metro" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
slack-lint-checks = { module = "com.slack.lint:slack-lint-checks", version.ref = "slack-lint" }
slack-lint-annotations = { module = "com.slack.lint:slack-lint-annotations", version.ref = "slack-lint" }
supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase" }
supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabase" }
supabase-storage = { module = "io.github.jan-tennert.supabase:storage-kt", version.ref = "supabase" }
test-androidx-ext = { module = "androidx.test.ext:junit", version.ref = "test-androidx-ext" }
test-androidx-runner = { module = "androidx.test:runner", version.ref = "test-androidx-runner" }
test-circuit = { module = "com.slack.circuit:circuit-test", version.ref = "circuit" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
test-truth = { module = "com.google.truth:truth", version.ref = "test-truth" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "cash-app-turbine" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
circuit = [
    "circuit-codegen-annotations",
    "circuit-foundation",
    "circuit-overlay",
    "circuit-retained",
    "circuit-runtime",
    "circuit-runtime-presenter",
    "circuit-runtime-screen",
    "circuit-runtime-ui",
    "circuitx-android",
    "circuitx-effects",
    "circuitx-gesture-navigation",
    "circuitx-overlays",
]
coil = [
    "coil-compose",
    "coil-okhttp",
]
compose = [
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",
    "androidx-compose-icons",
    "androidx-compose-icons-extended",
    "androidx-compose-material3",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-util",
    "androidx-compose-windowSizeClass",
    "androidx-lifecycle-runtime-compose"
]
compose-tooling = [
    "androidx-compose-tooling",
    "androidx-compose-tooling-preview",
]
haze = [
    "haze",
    "haze-materials",
]
common-lint = [
    "slack-lint-annotations",
    "slack-lint-checks",
    "lints-compose",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-android" }
android-library = { id = "com.android.library", version.ref = "gradle-android" }
foundry-base = { id = "com.slack.foundry.base", version.ref = "foundry" }
foundry-root = { id = "com.slack.foundry.root", version.ref = "foundry" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "google-firebase-crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
gradle-cache-fix = { id = "org.gradle.android.cache-fix", version.ref = "gradle-cache-fix" }
gradle-retry = { id = "org.gradle.test-retry", version.ref = "gradle-retry" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "sortDependencies" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
